# Generated by Django 2.1.2 on 2018-11-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='name',
            new_name='names',
        ),
    ]
