# Generated by Django 2.1.2 on 2018-11-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20181111_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item',
        ),
    ]
