# Generated by Django 2.1.2 on 2018-11-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_advert_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='hours',
            field=models.CharField(default='10:00AM – 08:00PM (Mon-Sat)', max_length=100),
        ),
    ]
