# Generated by Django 2.1.2 on 2018-10-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='item',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
